baseurl: ""
url: "https://mbbu.github.io"

title: MBBU
description: MBBU website

collections:
  cohorts:
    output: true

defaults:
  - scope:
      path: ""
      type: "cohorts"
    values:
      layout: "cohort"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 6
paginate_path: blog/page:num/

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
