baseurl: ""
url: "https://mbbu.github.io"

title: MBBU
description: MBBU website

collections:
  cohorts:
    output: true

defaults:
  - scope:
      path: ""
      type: "cohorts"
    values:
      layout: "cohort"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
